name: GCP Function deploy
on:
  push:
    branches: ["master"]

  workflow_dispatch:

jobs:
  deploy_to_gcp:
    name: "Deploy to GCP"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v4"

      - id: "auth"
        uses: "google-github-actions/auth@v3"
        with:
          project_id: ${{ vars.GCP_PROJECT }}
          workload_identity_provider: ${{secrets.GCP_ID_PROVIDER}}
          service_account: ${{secrets.GCP_DEPLOY_ACC}}

      - id: "setup-npm"
        uses: "actions/setup-node@v3"
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "./dns-updater-ts/package-lock.json"

      - id: "build"
        name: "Build function"
        working-directory: ./dns-updater-ts
        run: |
          npm ci
          npm run build

      - id: "setup-tofu"
        name: "Setup OpenTofu"
        uses: opentofu/setup-opentofu@v1

      - name: "Deploy solution"
        shell: bash
        working-directory: ./infrastructure
        env:
          TF_VAR_project: ${{ vars.GCP_PROJECT }}
          TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
        run: |
          tofu init
          tofu apply -input=false -compact-warnings -auto-approve
